<?php

namespace Phillopp\LaravelBanking\Sepa\PurposeCodes;

use Phillopp\LaravelBanking\Sepa\PurposeCode;

/**
 * SEPA-Purpose Code CGDD
 *
 * Transaction is related to a direct debit where the mandate was generated by using data from a payment card at the point of sale.
 */
class CGDD extends PurposeCode
{
    private string $code = 'CGDD';
    private string $description = 'Transaction is related to a direct debit where the mandate was generated by using data from a payment card at the point of sale.';
}